### ISSUE TITLE
http://coinmarketcap-nexuist.rhcloud.com/api/all

### ISSUE THREAD

**Issue by landomata** [Nexuist/CoinMarketCapAPI#10]
Not working returns:

{"error":"Requested coin does not exist or has not been updated yet."}

**Comment by Nexuist** [comment]
Whoops, sorry about that. Fixed with 7aa46a1dc4d174e2c02dd57ec314da85807316a1

**Comment by Cagy** [comment]
Not Found since 6 days on all api requests to https://coinmarketcap-nexuist.rhcloud.com/api/

Something changed?

**Comment by Nexuist** [comment]
Please check out #21
