### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by Newbb1** [Nexuist/CoinMarketCapAPI#12]
Error message when you try to contact the server.

**Comment by mandelmonkey** [comment]
Yes same here, if you could take a look soon that would be great

**Comment by NarubyRiverlione** [comment]
The problem is parsing the Banksys coin because it's symbol contain '@' .
I've created a pull request that solves this.
https://github.com/Nexuist/CoinMarketCapAPI/pull/13

**Comment by altsheets** [comment]
Oh wow, NarubyRiverlione, thank you so much.  Open source is so powerful.  
I am now using your repo instead, until @Nexuist is merging your pull request.
Thanks a lot!

**Comment by Nexuist** [comment]
Merged. Thank you very much for the help!
