### ISSUE TITLE
No Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by jrmccall** [Nexuist/CoinMarketCapAPI#16]
I'm developing a personal project that uses your API.  It worked fine when I was using Safari to develop it, but when I tried to test in Chrome or any other browser, I got this error: "No 'Access-Control-Allow-Origin' header is present on the requested resource."  I've done a bit of research into this, and most things I've found say that you have to change settings in the API server to enable CORS, but I obviously don't really have access to the server for this API.  I could be using it wrong, but here is what I am doing in my code.  Any advice?

 ```
 $.ajax({
     type: 'GET',
     url: "http://coinmarketcap-nexuist.rhcloud.com/api/all",
     processData: true,
     data: {},
     dataType: "json",
     success: function (data) {
         processData(data);
     }
 });

function processData(data){
      console.log(data);
      var btcvalg = data.btc.price.usd;
}

```

**Comment by Nexuist** [comment]
Hi,

Actually, the server supports Access-Control-Allow-Origin on every endpoint except the one you're hititng (/api/all). An alternative could be something like this:

```javascript
$.ajax({
    type: 'GET',
    url: "http://coinmarketcap-nexuist.rhcloud.com/api/btc/price",
    processData: true,
    data: {},
    dataType: "json",
    success: function (data) {
        processData(data);
    }
});

function processData(data){
     console.log(data);
     var btcvalg = data.usd;
}

```

Let me know if this works for you. If not, adding the proper headers to /api/all on my end should be simple enough.

**Comment by jrmccall** [comment]
Hi Andi,

Thanks for your reply.  That works.  However, I was using the all endpoint to be able to access multiple different coin values.  I just wanted to avoid having to send multiple requests and reduce the code size.  However, I can just send multiple requests if need be.

Thanks,

Jake McCall

**Comment by Nexuist** [comment]
Hey, I had a bit of free time so I was able to add those headers to /api/all (with 782044c23d461d18681cefab7ee6f78183c8989d). Let me know if that lets you query it without running into CORS issues.
