### ISSUE TITLE
Voxels just crashed

### ISSUE THREAD

**Issue by berdesos** [Nexuist/CoinMarketCapAPI#17]
Voxels just crashed [https://coinmarketcap-nexuist.rhcloud.com/api/vox](https://coinmarketcap-nexuist.rhcloud.com/api/vox)

**Comment by Nexuist** [comment]
Hi,

This is by design. As per the documentation:

<pre>A straightforward API to access market information for the <b>top 100</b> cryptocurrencies gathered from coinmarketcap.com. Updated every 5 minutes.</pre>

Voxels is currently hovering around rank 120 which is why the API doesn't crawl it.
