### ISSUE TITLE
Requested coin does not exist or has not been updated yet. BCAP token

### ISSUE THREAD

**Issue by adustyugov** [Nexuist/CoinMarketCapAPI#18]
http://coinmarketcap-nexuist.rhcloud.com/api/BCAP
Getting error with BCAP token, and with list of other less valuable tokens.

**Comment by berdesos** [comment]
this one as well [https://coinmarketcap-nexuist.rhcloud.com/api/vox](https://coinmarketcap-nexuist.rhcloud.com/api/vox)

**Comment by Nexuist** [comment]
Hi,

This is by design. As per the documentation:

<pre>A straightforward API to access market information for the <b>top 100</b> cryptocurrencies gathered from coinmarketcap.com. Updated every 5 minutes.</pre>

BCAP and Voxels are over rank 100 which is why they're not included.
