### ISSUE TITLE
Issues with outdated data for full names

### ISSUE THREAD

**Issue by lukeroge** [Nexuist/CoinMarketCapAPI#6]
I noticed if you use a full name instead of a ticker, you get outdated data.

https://coinmarketcap-nexuist.rhcloud.com/api/ltc

vs 

https://coinmarketcap-nexuist.rhcloud.com/api/litecoin

Is there any way you can flush this old data from your instance? Thanks :)

**Comment by lukeroge** [comment]
A nice idea would also be to store the full currency name in the API, and allow you to use that as a query and view it in the results. Slightly off-topic, though.

**Comment by Nexuist** [comment]
Closed with v2.0.
